site_name: "mlopt"
site_description: 'Machine Learning Optimizer'
site_author: "Bartolomeo Stellato"

pages:
  - Home: index.md

  - Getting started: getting_started.md

  - Manual:
    - Learners:
      - OptimalTreees: learners/optimal_trees.md
      - Pytorch: learners/pytorch.md

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'light blue'



repo_name: 'bstellato/mlopt'
repo_url: 'https://github.com/bstellato/mlopt'


extra:
  social:
    - type: 'github'
      link: 'https://github.com/bstellato'



copyright: 'Copyright &copy; 2020 Bartolomeo Stellato'

